export const ADD_BLETCHLEY_INDEX = "ADD_BLETCHLEY_INDEX"
export const REMOVE_BLETCHLEY_INDEX = "REMOVE_BLETCHLEY_INDEX"

export const ADD_BLETCHLEY_MEMBER = "ADD_BLETCHLEY_MEMBER"
export const REMOVE_BLETCHLEY_MEMBER = "REMOVE_BLETCHLEY_MEMBER"
