
export const ADD_INDEXES = "ADD_BLETCHLEY_INDEXES"
export const ADD_CURRENCY_SYMBOLS = "ADD_CRYPTOCURRENCY_SYMBOLS"
export const ADD_INDEX_UPDATES = "ADD_BLETCHLEY_INDEX_UPDATES"

/**
export const ADD_BLETCHLEY_INDEX = "ADD_BLETCHLEY_INDEX"
export const REMOVE_BLETCHLEY_INDEX = "REMOVE_BLETCHLEY_INDEX"

export const ADD_BLETCHLEY_MEMBER = "ADD_BLETCHLEY_MEMBER"
export const REMOVE_BLETCHLEY_MEMBER = "REMOVE_BLETCHLEY_MEMBER"
**/
